#!/usr/bin/env python3
"""
Archeve — Site Data Pack.

Given a site polygon, clip the GCN250 Curve Number raster to it and derive the
SCS-CN hydrology grids the screening reports reference, as GeoTIFFs zipped for
download into GIS (QGIS / ArcGIS):

  cn_arcii.tif   — Curve Number, ARC II (from GCN250, 250 m)
  retention_S.tif — potential maximum retention S = 25400/CN - 254   (mm)
  ia_initial_abstraction.tif — initial abstraction Ia = 0.2 * S      (mm)

All grids share the clipped GCN250 grid (EPSG:4326, ~250 m). Screening-grade —
GCN250 is a global product, not a surveyed CN map.

DEM (30 m), Manning's n and flood-hazard classification are served separately
(they draw on other rasters) — this module owns the CN-derived layers.
"""
import os
import io
import zipfile
import tempfile

import numpy as np
import rasterio
from rasterio.mask import mask
from shapely.geometry import shape, mapping

import gcn_zonal as gz

NODATA_CN = 255
NODATA_F = -9999.0
MAX_DEG = gz.MAX_DEG


def _write_geotiff(path, arr, transform, crs, nodata):
    with rasterio.open(
        path, "w", driver="GTiff", height=arr.shape[0], width=arr.shape[1],
        count=1, dtype=arr.dtype, crs=crs, transform=transform, nodata=nodata,
        compress="deflate",
    ) as dst:
        dst.write(arr, 1)


def build(geom, path=None):
    """geom: GeoJSON geometry (WGS84). Returns (zip_path, meta) or (None, error_dict)."""
    path = path or gz.GCN250_PATH
    if not os.path.exists(path):
        try:
            gz.ensure_raster()
        except Exception as e:
            return None, {"ok": False, "error": "GCN250 raster fetch failed: %s" % e}
    if not os.path.exists(path):
        return None, {"ok": False, "error": "GCN250 raster not available."}

    try:
        g = shape(geom)
    except Exception as e:
        return None, {"ok": False, "error": "bad geometry: %s" % e}
    if g.is_empty:
        return None, {"ok": False, "error": "empty geometry"}
    minx, miny, maxx, maxy = g.bounds
    if (maxx - minx) > MAX_DEG or (maxy - miny) > MAX_DEG:
        return None, {"ok": False, "error": "bbox too large for screening (> %.1f deg)" % MAX_DEG}

    with rasterio.open(path) as ds:
        try:
            out, transform = mask(ds, [mapping(g)], crop=True, nodata=NODATA_CN, filled=True)
        except Exception as e:
            return None, {"ok": False, "error": "raster mask failed: %s" % e}
        crs = ds.crs

    cn = out[0].astype("float32")
    valid = (cn > 0) & (cn <= 100)
    if not valid.any():
        return None, {"ok": False, "error": "no valid CN pixels under the polygon (water / no-data)"}

    # SCS-CN derived grids
    cn_out = np.where(valid, cn, NODATA_F).astype("float32")
    S = np.where(valid, 25400.0 / np.where(valid, cn, 1.0) - 254.0, NODATA_F).astype("float32")  # mm
    Ia = np.where(valid, 0.2 * np.where(valid, 25400.0 / np.where(valid, cn, 1.0) - 254.0, 0.0), NODATA_F).astype("float32")

    tmpdir = tempfile.mkdtemp(prefix="datapack_")
    files = {
        "cn_arcii.tif": cn_out,
        "retention_S.tif": S,
        "ia_initial_abstraction.tif": Ia,
    }
    for name, arr in files.items():
        _write_geotiff(os.path.join(tmpdir, name), arr, transform, crs, NODATA_F)

    readme = (
        "Archeve — Site Data Pack (SCS-CN grids)\n"
        "========================================\n\n"
        "cn_arcii.tif                 Curve Number, Antecedent Runoff Condition II\n"
        "retention_S.tif              Potential maximum retention S = 25400/CN - 254  (mm)\n"
        "ia_initial_abstraction.tif   Initial abstraction Ia = 0.2 * S  (mm)\n\n"
        "Grid: EPSG:4326, ~250 m (GCN250, Jaafar, Ahmad & El Beyrouthy 2019, CC BY 4.0).\n"
        "NoData = -9999. Screening-grade — GCN250 is a global product, not a surveyed CN map.\n"
        "Verify against local land use and surveyed soils before design.\n\n"
        "Generated by Archeve AIP — aip.archeve.in\n"
    )
    open(os.path.join(tmpdir, "README.txt"), "w").write(readme)

    zip_path = os.path.join(tmpdir, "archeve_site_datapack.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for name in list(files) + ["README.txt"]:
            z.write(os.path.join(tmpdir, name), name)

    meta = {
        "ok": True,
        "layers": ["cn_arcii", "retention_S", "ia_initial_abstraction"],
        "grid": "EPSG:4326 ~250 m (GCN250)",
        "n_pixels": int(valid.sum()),
        "cn_mean": round(float(cn[valid].mean()), 1),
    }
    return zip_path, meta
